version: '3.9'

services:
  database:
    image: postgres:latest  
    container_name: postgres_db_boersenparty
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bparty
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:
