name: Build, push and deploy

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    name: Build app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master

      - name: Prepare repository name
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV         

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest
            ghcr.io/${{ env.IMAGE_REPOSITORY }}:${{ env.BRANCH_NAME }}
